"""add updated_at to app.models.Customer

Revision ID: 403fd8c7bd9a
Revises: dfae6a930553
Create Date: 2026-02-09 09:50:48.876912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '403fd8c7bd9a'
down_revision: Union[str, Sequence[str], None] = 'dfae6a930553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'updated_at')
    # ### end Alembic commands ###
