"""update models -> add field updated_at to app.models.Order

Revision ID: 79f3893f7467
Revises: 403fd8c7bd9a
Create Date: 2026-02-09 11:18:45.070685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79f3893f7467'
down_revision: Union[str, Sequence[str], None] = '403fd8c7bd9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'updated_at')
    # ### end Alembic commands ###
